version: '3'
services:
  postgres-db:
    container_name: car-service-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: car
      POSTGRES_DB: car
      POSTGRES_PASSWORD: car
