version: '3'
services:
  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:          
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
